Add Hex Support
ByronBecker/motoko-color pull request #1
Opened 2022-05-12 23:12 UTC by tomijaga

Hey, I thought it would be useful if users could also enter hex values to set styles.
I imported the hex library
The reason I added this feature to the library was because I was using it in my program and had a list of preselected colors I wanted to choose from. These colors were stored as hex values and I thought it would be really inefficient and time-consuming to convert them all to rbg. I thought about other people that who might run into this issue in future so I decided to make a pr with support for hex values. 

#### Added Methods :
- `textColorHex: (hex: Text) -> TextStyleFunctor`
- `backgroundColorHex: (hex: Text) -> TextStyleFunctor`

Both functions take in a 6 letter hex string value, which can be prefixed by `#` to make 7 letters. Both functions are case insensitive so the hex values can be in lowercase or uppercase.

For a red color with hex `ff0101`, the following values are accepted
- `"#FF0101"` 
- `"#ff0101"` 
- `"FF0101"`
- `"ff0101"`

#### Example
- code
```motoko
    Writer()
        .text("- error")
        .backgroundColorHex("#FF0101")
        .print()
```

- terminal
```diff
- error
```
#### Error Handling
An issue however is that the hex entered by the user could be incorrect. And in most case the solution is to return a `Result` type that contains an error. However, I didn't want to alter the current return type of the functor so I wrote code to ignore the hex value and just return the previous settings. I don't think this is the best method of error handling as it could leave the user puzzled on what went wrong so I'm curious to know other ways error handling could be approached in the library.

2022-06-06 06:30 UTC, ByronBecker commented
Hey @tomijaga this is a great idea and I'd love to incorporate it, sorry for missing this earlier.

I reviewed it and everything looks good to me. I'd love to merge in this feature if you still want to contribute - can you re-submit this work as a single commit and ping me if so?

Also, in the future if I'm not responsive here, please DM me on the developer Discord at username "canscale" or on the developer forums at username "icme".

2022-06-06 06:33 UTC, ByronBecker requested changes
@tomijaga One small change, then looks good otherwise!

2022-06-06 06:33 UTC, ByronBecker commented on src/Writer.mo
> +          if (bytes.size == 3){
It looks like you have a small error here. Changing `bytes.size` to `bytes.size()` should fix it!

2022-06-08 01:18 UTC, tomijaga commented
Hey @ByronBecker, thanks for reviewing this feature and sharing your contact information with me. I have made the requested change to the `size()` method and submitted a new pull request with a single commit.

2022-06-08 06:57 UTC, ByronBecker commented
Closing as https://github.com/ByronBecker/motoko-color/pull/2 was merged in

2022-06-08 06:57 UTC, closed without merging